apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {name}
  labels: 
     app: {app}

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: {app}

  template:
    metadata:
      labels:
        app: {app}
    spec:
      containers:
      - name: {app}
        image: {user}/{your file name}#the one in docker hub
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1